ALTER TABLE `players` ADD `guild` INT( 8 ) UNSIGNED NOT NULL DEFAULT '0' AFTER `marriage` ,
ADD `guild_rank` TINYINT( 4 ) UNSIGNED NOT NULL DEFAULT '0' AFTER `guild` ;

CREATE TABLE `houses` (
`id` INT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`owner` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
`guild` INT( 8 ) UNSIGNED NOT NULL DEFAULT '0',
`paid` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
`name` VARCHAR( 64 ) NOT NULL ,
`town` INT( 8 ) UNSIGNED NOT NULL DEFAULT '0',
`size` INT( 8 ) UNSIGNED NOT NULL ,
`rent` INT( 11 ) UNSIGNED NOT NULL ,
`data` BLOB NULL DEFAULT NULL ,
`price` INT( 11 ) UNSIGNED NOT NULL DEFAULT '0',
`for_sale` TINYINT( 1 ) UNSIGNED NOT NULL DEFAULT '0'
) ENGINE = MYISAM ;

