CREATE TABLE `groups` (
`group_id` INT( 11 ) UNSIGNED NOT NULL ,
`group_name` VARCHAR( 48 ) NOT NULL ,
`group_flags` TEXT NOT NULL ,
PRIMARY KEY ( `group_id` ) ,
INDEX ( `group_name` )
) ENGINE = InnoDB;

INSERT INTO `groups` (`group_id`, `group_name`, `group_flags`) VALUES
(1, 'Player', '["SAVESELF", "HOUSE", "PREMIUM", "SPELLS", "SPEAK", "MOVE_ITEMS", "LOOT", "ATTACK"]'),
(2, 'Tutor', '["SAVESELF", "HOUSE", "PREMIUM", "SPELLS", "SPEAK", "MOVE_ITEMS", "LOOT", "ATTACK"]'),
(3, 'Community Manager', '["MUTE", "TELEPORT", "IMMUNE", "NO_EXHAUST", "IGNORED_BY_CREATURES", "TALK_ORANGE", "SPEED", "SAVESELF", "SPEAK", "MOVE_ITEMS"]'),
(4, 'Gamemaster', '["CREATEITEM", "TELEPORT", "SETHOUSEOWNER", "SAVEALL", "SAVESELF", "SPAWN", "RAID", "HOUSE", "KICK", "BAN", "MUTE", "PREMIUM", "SPELLS", "SPEAK", "SPEED", "MOVE_ITEMS", "LOOT", "INVISIBLE", "INFINATE_SOUL", "INFINATE_MANA", "INFINATE_HEALTH", "INFINATE_STAMINA", "ATTACK", "IGNORED_BY_CREATURES", "TALK_ORANGE", "TALK_RED", "IMMUNE", "NO_EXHAUST"]'),
(5, 'God', '["CREATEITEM", "TELEPORT", "SETHOUSEOWNER", "SAVEALL", "SAVESELF", "SPAWN", "RAID", "HOUSE", "MANAGESERVER", "MODIFYMAP", "KICK", "RELOAD", "BAN", "MUTE", "DEVELOPER", "PREMIUM", "SPELLS", "SPEAK", "SPEED", "MOVE_ITEMS", "LOOT", "INVISIBLE", "INFINATE_SOUL", "INFINATE_MANA", "INFINATE_HEALTH", "INFINATE_STAMINA", "ATTACK", "IGNORED_BY_CREATURES", "TALK_ORANGE", "TALK_RED", "IMMUNE", "NO_EXHAUST"]'),
(6, 'Admin', '["CREATEITEM", "TELEPORT", "SETHOUSEOWNER", "SAVEALL", "SAVESELF", "SPAWN", "RAID", "HOUSE", "MANAGESERVER", "MODIFYMAP", "KICK", "RELOAD", "BAN", "MUTE", "DEVELOPER", "PREMIUM", "SPELLS", "SPEAK", "SPEED", "MOVE_ITEMS", "LOOT", "INVISIBLE", "INFINATE_SOUL", "INFINATE_MANA", "INFINATE_HEALTH", "INFINATE_STAMINA", "ATTACK", "IGNORED_BY_CREATURES", "TALK_ORANGE", "TALK_RED", "IMMUNE", "NO_EXHAUST"]');
